### ISSUE TITLE
I have a question related to the tag

### ISSUE THREAD

**Issue by youngjaean** [douwekiela/mmfeat#11]
Is this the code that gets photos from Flickr image only? 
i want get tag , but is it impossible?

**Comment by douwekiela** [comment]
This repository is slightly outdated, so I would advise using something that stays up to date with respect to the Flickr API, such as https://github.com/alexis-mignon/python-flickr-api.

However, to answer your question, it is querying for the 'text', as the first parameter says in the miner: https://github.com/douwekiela/mmfeat/blob/master/mmfeat/miner/flickr.py#L58. You can change 'text' to 'tags' and then it will search for tags only.

See here for the Flickr API documentation: https://www.flickr.com/services/api/flickr.photos.search.html. Using the above Python library, you would do something like:

```
import flickr_api as flickr
flickr.set_keys(api_key='XXX', api_secret='XXX')
photos = flickr.Photo.search(tags='your keyword(s)')
for num, photo in enumerate(photos):
    photo.save('%s_%s' % (tag, num))
```

Hope that helps!

**Comment by youngjaean** [comment]
thank you for your answer!
