### ISSUE TITLE
"nan" image dispersion value for the word "kindness"

### ISSUE THREAD

**Issue by benbuleong** [douwekiela/mmfeat#5]
I experimented with the demo scripts and used a random seed of 200 words for computing their image dispersion values. This was done using `GoogleMiner`. For some reasons, even though there are images retrieved for the word "kindness", its value returned is nan. I have yet to find out the cause, but would like to report this as a possible issue here.

**Comment by douwekiela** [comment]
Hi Ben, that's strange, thanks for reporting.. Is this using CNN or BoVW? There are either nan's in the image representations or there is a division by zero somewhere, which should be solved by callling np.nan_to_num in the appropriate place(s).

**Comment by benbuleong** [comment]
Hi Douwe, it happens during the BoVW generation. It is strange because manual inspection of the images suggests that they are fine and pretty relevant. I haven't got the chance to look deeper into the codes yet, but when I do, I would try to fix it and do a PR.

**Comment by douwekiela** [comment]
Interesting, what happens when you do `np.isnan(np.min(x))` on the descriptors? If you'd like me to have a look feel free to e-mail me the descriptors file!

**Comment by benbuleong** [comment]
Hi @douwekiela, sorry for the delay. Here are the [descriptors](http://benleong.net/mmfeat/kindness_descriptors.tar.gz).

**Comment by benbuleong** [comment]
Hi @douwekiela, this issue had been solved with the latest commit. I re-cloned and re-run the demo.py script, and all dispersion scores for the 200 words are generated.  Thanks!
