### ISSUE TITLE
Flickr API gives duplicates when query returns more than 4,000 results.

### ISSUE THREAD

**Issue by 15kingben** [douwekiela/mmfeat#9]
According to the [documentation](https://www.flickr.com/services/api/flickr.photos.search.html) the Flickr API will return at most 4,000 results for a given query, with the rest after that being duplicates. That seems to be corroborated by my testing, although occasionally it weirdly works correctly. To download more than 4k pictures the query should be split into date ranges or other smaller queries with less than 4k results.

**Comment by douwekiela** [comment]
We didn't really consider use-cases of that many images. I would welcome a PR that addresses this - is there a dynamic way to break the query up into smaller queries?
